sonar.projectKey=FleetOps-Request-Service
sonar.projectName=FleetOps Request Service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/target/**,**/build/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
